services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - neo4j_data:/data

  app:
    build: .
    container_name: stapp
    depends_on:
      - neo4j
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app
    command: ["streamlit", "run", "robotapp.py"]

volumes:
  neo4j_data: